[package]
name = "saltz"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
ron = "0.12.0"
serde = "1.0.219"
serde_derive = "1.0.219"
users = "0.11.0"
