[package]
name = "saltz"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
serde = "1.0.219"
serde_derive = "1.0.219"
toml = "0.8.23"
users = "0.11.0"
